create table if not exists public.rate_limit_events (
    id bigint generated by default as identity primary key,
    client_hash text not null,
    scope text not null,
    created_at timestamp with time zone not null default now()
);

create index if not exists rate_limit_events_lookup_idx
    on public.rate_limit_events (scope, client_hash, created_at desc);

alter table public.rate_limit_events enable row level security;
