create table if not exists public.system_info (
    id bigint generated by default as identity primary key,
    topic varchar(255),
    content text
);

create table if not exists public.project (
    id bigint generated by default as identity primary key,
    title varchar(255),
    description text,
    technology varchar(255),
    url varchar(255),
    image_url varchar(255)
);

create table if not exists public.message (
    id bigint generated by default as identity primary key,
    content text,
    sender varchar(255),
    timestamp timestamp with time zone,
    metadata varchar(1000),
    constraint message_sender_check check (sender in ('USER', 'ASSISTANT'))
);

alter table public.system_info enable row level security;
alter table public.project enable row level security;
alter table public.message enable row level security;
